# Generated by Django 6.0.4 on 2026-05-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer_type',
            field=models.CharField(choices=[('Retail', 'Retail'), ('Wholesale', 'Wholesale')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
